{{- if .Values.secret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "api-management-service.secretName" . }}
  labels:
    {{- include "api-management-service.labels" . | nindent 4 }}
    app.kubernetes.io/component: api-management
    app.kubernetes.io/part-of: microservices
type: Opaque
data:
  {{- range $key, $value := .Values.secret.data }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
{{- end }}
